Repository openshift/tektoncd-catalog, pull requests merged in 2019-12, with the labels that each got.

#73 Add pipelines catalog tasks into here
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#78 More robust detection for nightly yaml release
  openshift/Makefile
  openshift/pipeline-latest-release.sh
Labels: approved, lgtm, size/M

#94 New create release script
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/M

#99 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#100 Bump to golang 1.13
  openshift/Dockerfile
Labels: approved, lgtm, size/XS
