Repository openshift/tektoncd-catalog, pull requests merged in 2019-11, with the labels that each got.

#53 Install pipeline and run e2e test
  openshift/Makefile
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#55 Fix path and change permission
  openshift/Makefile
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#56 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#59 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#58 Rework downstream E2E tests
  openshift/Makefile
  openshift/e2e-add-service-account.py
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#66 Readd S2I
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#68 User serviceAccountName instead of serviceAccount
  openshift/e2e-add-service-account.py
Labels: approved, lgtm, size/XS

#69 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS
