Repository openshift/tektoncd-catalog, pull requests merged in 2020-03, with the labels that each got.

#164 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: do-not-merge/invalid-owners-file, kind/sync-fork-to-upstream, size/XS

#168 Be explicit about what gets pushed where
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/S

#172 Change max shift variable to 2
  openshift/pipeline-latest-release.sh
Labels: approved, lgtm

#176 Use tag based url
  openshift/pipeline-latest-release.sh
Labels: approved, lgtm
